import { AreaType } from "./type";

export const AREA_LV1: { [key: string]: AreaType } = {
  seoul: { rcode: 10000, areaLv: 1, name: { en: "seoul", kr: "서울특별시" } },
  incheon: { rcode: 20000, areaLv: 1, name: { en: "incheon", kr: "인천광역시" } },
  daejeon: { rcode: 30000, areaLv: 1, name: { en: "daejeon", kr: "대전광역시" } },
  daegu: { rcode: 40000, areaLv: 1, name: { en: "daegu", kr: "대구광역시" } },
  ulsan: { rcode: 50000, areaLv: 1, name: { en: "ulsan", kr: "울산광역시" } },
  busan: { rcode: 60000, areaLv: 1, name: { en: "busan", kr: "부산광역시" } },
  gwangju: { rcode: 70000, areaLv: 1, name: { en: "gwangju", kr: "광주광역시" } },
  sejong: { rcode: 80000, areaLv: 1, name: { en: "sejong", kr: "세종특별자치시" } },
  gyeonggi: { rcode: 90000, areaLv: 1, name: { en: "gyeonggi", kr: "경기도" } },
  gangwon: { rcode: 100000, areaLv: 1, name: { en: "gangwon", kr: "강원도" } },
  northChungcheong: { rcode: 110000, areaLv: 1, name: { en: "northChungcheong", kr: "충청북도" } },
  southChungcheong: { rcode: 120000, areaLv: 1, name: { en: "southChungcheong", kr: "충청남도" } },
  northGyeongsang: { rcode: 130000, areaLv: 1, name: { en: "northGyeongsang", kr: "경상북도" } },
  southGyeongsang: { rcode: 140000, areaLv: 1, name: { en: "southGyeongsang", kr: "경상남도" } },
  northJeolla: { rcode: 150000, areaLv: 1, name: { en: "northJeolla", kr: "전라북도" } },
  southJeolla: { rcode: 160000, areaLv: 1, name: { en: "southJeolla", kr: "전라남도" } },
  jeju: { rcode: 170000, areaLv: 1, name: { en: "jeju", kr: "제주특별자치도" } },
};

export const AREA_LV2: { [key: string]: AreaType[] } = {
  seoul: [
    { rcode: 10100, areaLv: 2, name: { en: "gangnam", kr: "강남구" } },
    { rcode: 10200, areaLv: 2, name: { en: "gangdong", kr: "강동구" } },
    { rcode: 10300, areaLv: 2, name: { en: "gangbuk", kr: "강북구" } },
    { rcode: 10400, areaLv: 2, name: { en: "gangseo", kr: "강서구" } },
    { rcode: 10500, areaLv: 2, name: { en: "gwanak", kr: "관악구" } },
    { rcode: 10600, areaLv: 2, name: { en: "gwangjin", kr: "광진구" } },
    { rcode: 10700, areaLv: 2, name: { en: "guro", kr: "구로구" } },
    { rcode: 10800, areaLv: 2, name: { en: "geumcheon", kr: "금천구" } },
    { rcode: 10900, areaLv: 2, name: { en: "nowon", kr: "노원구" } },
    { rcode: 11000, areaLv: 2, name: { en: "dobong", kr: "도봉구" } },
    { rcode: 11100, areaLv: 2, name: { en: "dongdaemun", kr: "동대문구" } },
    { rcode: 11200, areaLv: 2, name: { en: "dongjak", kr: "동작구" } },
    { rcode: 11300, areaLv: 2, name: { en: "mapo", kr: "마포구" } },
    { rcode: 11400, areaLv: 2, name: { en: "seodaemun", kr: "서대문구" } },
    { rcode: 11500, areaLv: 2, name: { en: "seocho", kr: "서초구" } },
    { rcode: 11600, areaLv: 2, name: { en: "seongdong", kr: "성동구" } },
    { rcode: 11700, areaLv: 2, name: { en: "seongbuk", kr: "성북구" } },
    { rcode: 11800, areaLv: 2, name: { en: "songpa", kr: "송파구" } },
    { rcode: 11900, areaLv: 2, name: { en: "yangcheon", kr: "양천구" } },
    { rcode: 12000, areaLv: 2, name: { en: "yeongdeungpo", kr: "영등포구" } },
    { rcode: 12100, areaLv: 2, name: { en: "yongsan", kr: "용산구" } },
    { rcode: 12200, areaLv: 2, name: { en: "eunpyeong", kr: "은평구" } },
    { rcode: 12300, areaLv: 2, name: { en: "jongno", kr: "종로구" } },
    { rcode: 12400, areaLv: 2, name: { en: "jung", kr: "중구" } },
    { rcode: 12500, areaLv: 2, name: { en: "jungnang", kr: "중랑구" } },
  ],
  incheon: [
    { rcode: 20100, areaLv: 2, name: { en: "gyeyang", kr: "계양구" } },
    { rcode: 20200, areaLv: 2, name: { en: "nam", kr: "남구" } },
    { rcode: 20300, areaLv: 2, name: { en: "namdong", kr: "남동구" } },
    { rcode: 20400, areaLv: 2, name: { en: "dong", kr: "동구" } },
    { rcode: 20500, areaLv: 2, name: { en: "bupyeong", kr: "부평구" } },
    { rcode: 20600, areaLv: 2, name: { en: "seo", kr: "서구" } },
    { rcode: 20700, areaLv: 2, name: { en: "yeonsu", kr: "연수구" } },
    { rcode: 20800, areaLv: 2, name: { en: "jung", kr: "중구" } },
    { rcode: 20900, areaLv: 2, name: { en: "ganghwa", kr: "강화군" } },
    { rcode: 21000, areaLv: 2, name: { en: "ongjin", kr: "옹진군" } },
  ],
  daejeon: [
    { rcode: 30100, areaLv: 2, name: { en: "daedeok", kr: "대덕구" } },
    { rcode: 30200, areaLv: 2, name: { en: "dong", kr: "동구" } },
    { rcode: 30300, areaLv: 2, name: { en: "seo", kr: "서구" } },
    { rcode: 30400, areaLv: 2, name: { en: "yuseong", kr: "유성구" } },
    { rcode: 30500, areaLv: 2, name: { en: "jung", kr: "중구" } },
  ],
  daegu: [
    { rcode: 40100, areaLv: 2, name: { en: "nam", kr: "남구" } },
    { rcode: 40200, areaLv: 2, name: { en: "dalseo", kr: "달서구" } },
    { rcode: 40300, areaLv: 2, name: { en: "dong", kr: "동구" } },
    { rcode: 40400, areaLv: 2, name: { en: "buk", kr: "북구" } },
    { rcode: 40500, areaLv: 2, name: { en: "seo", kr: "서구" } },
    { rcode: 40600, areaLv: 2, name: { en: "suseong", kr: "수성구" } },
    { rcode: 40700, areaLv: 2, name: { en: "jung", kr: "중구" } },
    { rcode: 40800, areaLv: 2, name: { en: "dalseong", kr: "달성군" } },
  ],
  ulsan: [
    { rcode: 50100, areaLv: 2, name: { en: "nam", kr: "남구" } },
    { rcode: 50200, areaLv: 2, name: { en: "dong", kr: "동구" } },
    { rcode: 50300, areaLv: 2, name: { en: "buk", kr: "북구" } },
    { rcode: 50400, areaLv: 2, name: { en: "jung", kr: "중구" } },
    { rcode: 50500, areaLv: 2, name: { en: "ulju", kr: "울주군" } },
  ],
  busan: [
    { rcode: 60100, areaLv: 2, name: { en: "gangseo", kr: "강서구" } },
    { rcode: 60200, areaLv: 2, name: { en: "gumjung", kr: "금정구" } },
    { rcode: 60300, areaLv: 2, name: { en: "nam", kr: "남구" } },
    { rcode: 60400, areaLv: 2, name: { en: "dong", kr: "동구" } },
    { rcode: 60500, areaLv: 2, name: { en: "dongnae", kr: "동래구" } },
    { rcode: 60600, areaLv: 2, name: { en: "busanjin", kr: "부산진구" } },
    { rcode: 60700, areaLv: 2, name: { en: "buk", kr: "북구" } },
    { rcode: 60800, areaLv: 2, name: { en: "sasang", kr: "사상구" } },
    { rcode: 60900, areaLv: 2, name: { en: "saha", kr: "사하구" } },
    { rcode: 61000, areaLv: 2, name: { en: "seo", kr: "서구" } },
    { rcode: 61100, areaLv: 2, name: { en: "suyeong", kr: "수영구" } },
    { rcode: 61200, areaLv: 2, name: { en: "yeonje", kr: "연제구" } },
    { rcode: 61300, areaLv: 2, name: { en: "yeongdo", kr: "영도구" } },
    { rcode: 61400, areaLv: 2, name: { en: "jung", kr: "중구" } },
    { rcode: 61500, areaLv: 2, name: { en: "haeundae", kr: "해운대구" } },
    { rcode: 61600, areaLv: 2, name: { en: "gijang", kr: "기장군" } },
  ],
  gwangju: [
    { rcode: 70100, areaLv: 2, name: { en: "gwangsan", kr: "광산구" } },
    { rcode: 70200, areaLv: 2, name: { en: "nam", kr: "남구" } },
    { rcode: 70300, areaLv: 2, name: { en: "dong", kr: "동구" } },
    { rcode: 70400, areaLv: 2, name: { en: "buk", kr: "북구" } },
    { rcode: 70500, areaLv: 2, name: { en: "seo", kr: "서구" } },
  ],
  sejong: [],
  gyeonggi: [
    { rcode: 90100, areaLv: 2, name: { en: "gapyeong", kr: "가평시" } },
    { rcode: 90200, areaLv: 2, name: { en: "goyang", kr: "고양시" } },
    { rcode: 90300, areaLv: 2, name: { en: "gwacheon", kr: "과천시" } },
    { rcode: 90400, areaLv: 2, name: { en: "gwangmyeong", kr: "광명시" } },
    { rcode: 90500, areaLv: 2, name: { en: "gwangju", kr: "광주시" } },
    { rcode: 90600, areaLv: 2, name: { en: "guri", kr: "구리시" } },
    { rcode: 90700, areaLv: 2, name: { en: "gunpo", kr: "군포시" } },
    { rcode: 90800, areaLv: 2, name: { en: "gimpo", kr: "김포시" } },
    { rcode: 90900, areaLv: 2, name: { en: "namyangju", kr: "남양주시" } },
    { rcode: 91000, areaLv: 2, name: { en: "dongducheon", kr: "동두천시" } },
    { rcode: 91100, areaLv: 2, name: { en: "bucheon", kr: "부천시" } },
    { rcode: 91200, areaLv: 2, name: { en: "seongnam", kr: "성남시" } },
    { rcode: 91300, areaLv: 2, name: { en: "suwon", kr: "수원시" } },
    { rcode: 91400, areaLv: 2, name: { en: "siheung", kr: "시흥시" } },
    { rcode: 91500, areaLv: 2, name: { en: "ansan", kr: "안산시" } },
    { rcode: 91600, areaLv: 2, name: { en: "anseong", kr: "안성시" } },
    { rcode: 91700, areaLv: 2, name: { en: "anyang", kr: "안양시" } },
    { rcode: 91800, areaLv: 2, name: { en: "yangju", kr: "양주시" } },
    { rcode: 91900, areaLv: 2, name: { en: "yeoju", kr: "여주시" } },
    { rcode: 92000, areaLv: 2, name: { en: "osan", kr: "오산시" } },
    { rcode: 92100, areaLv: 2, name: { en: "yongin", kr: "용인시" } },
    { rcode: 92200, areaLv: 2, name: { en: "uiwang", kr: "의왕시" } },
    { rcode: 92300, areaLv: 2, name: { en: "uijeongbu", kr: "의정부시" } },
    { rcode: 92400, areaLv: 2, name: { en: "icheon", kr: "이천시" } },
    { rcode: 92500, areaLv: 2, name: { en: "paju", kr: "파주시" } },
    { rcode: 92600, areaLv: 2, name: { en: "pyeongtaek", kr: "평택시" } },
    { rcode: 92700, areaLv: 2, name: { en: "pocheon", kr: "포천시" } },
    { rcode: 92800, areaLv: 2, name: { en: "hanam", kr: "하남시" } },
    { rcode: 92900, areaLv: 2, name: { en: "hwaseong", kr: "화성시" } },
    { rcode: 93000, areaLv: 2, name: { en: "yangpyeong", kr: "양평군" } },
    { rcode: 93100, areaLv: 2, name: { en: "yeoncheon", kr: "여천군" } },
  ],
  gangwon: [
    { rcode: 100100, areaLv: 2, name: { en: "gangneung", kr: "강릉시" } },
    { rcode: 100200, areaLv: 2, name: { en: "donghae", kr: "동해시" } },
    { rcode: 100300, areaLv: 2, name: { en: "samcheok", kr: "삼척시" } },
    { rcode: 100400, areaLv: 2, name: { en: "sokcho", kr: "속초시" } },
    { rcode: 100500, areaLv: 2, name: { en: "wonju", kr: "원주시" } },
    { rcode: 100600, areaLv: 2, name: { en: "chuncheon", kr: "춘천시" } },
    { rcode: 100700, areaLv: 2, name: { en: "taebaek", kr: "태백시" } },
    { rcode: 100800, areaLv: 2, name: { en: "goseong", kr: "고성군" } },
    { rcode: 100900, areaLv: 2, name: { en: "yanggu", kr: "양구군" } },
    { rcode: 101000, areaLv: 2, name: { en: "yangyang", kr: "양양군" } },
    { rcode: 101100, areaLv: 2, name: { en: "yeongwol", kr: "영월군" } },
    { rcode: 101200, areaLv: 2, name: { en: "inje", kr: "인제군" } },
    { rcode: 101300, areaLv: 2, name: { en: "jeongseon", kr: "정선군" } },
    { rcode: 101400, areaLv: 2, name: { en: "cheorwon", kr: "철원군" } },
    { rcode: 101500, areaLv: 2, name: { en: "pyeongchang", kr: "평창군" } },
    { rcode: 101600, areaLv: 2, name: { en: "hongcheon", kr: "홍천군" } },
    { rcode: 101700, areaLv: 2, name: { en: "hwacheon", kr: "화천군" } },
    { rcode: 101800, areaLv: 2, name: { en: "hoengseong", kr: "횡성군" } },
  ],
  northChungcheong: [
    { rcode: 110100, areaLv: 2, name: { en: "jecheon", kr: "제천시" } },
    { rcode: 110200, areaLv: 2, name: { en: "cheongju", kr: "청주시" } },
    { rcode: 110300, areaLv: 2, name: { en: "chungju", kr: "충주시" } },
    { rcode: 110400, areaLv: 2, name: { en: "goesan", kr: "괴산군" } },
    { rcode: 110500, areaLv: 2, name: { en: "danyang", kr: "단양군" } },
    { rcode: 110600, areaLv: 2, name: { en: "boeun", kr: "보은군" } },
    { rcode: 110700, areaLv: 2, name: { en: "yeongdong", kr: "영동군" } },
    { rcode: 110800, areaLv: 2, name: { en: "okcheon", kr: "옥천군" } },
    { rcode: 110900, areaLv: 2, name: { en: "eumseong", kr: "음성군" } },
    { rcode: 111000, areaLv: 2, name: { en: "jeungpyeong", kr: "증평군" } },
    { rcode: 111100, areaLv: 2, name: { en: "jincheon", kr: "진천군" } },
  ],
  southChungcheong: [
    { rcode: 120100, areaLv: 2, name: { en: "gyeryong", kr: "계룡시" } },
    { rcode: 120200, areaLv: 2, name: { en: "gongju", kr: "공주시" } },
    { rcode: 120300, areaLv: 2, name: { en: "nonsan", kr: "논산시" } },
    { rcode: 120400, areaLv: 2, name: { en: "dangjin", kr: "당진시" } },
    { rcode: 120500, areaLv: 2, name: { en: "boryeong", kr: "보령시" } },
    { rcode: 120600, areaLv: 2, name: { en: "seosan", kr: "서산시" } },
    { rcode: 120700, areaLv: 2, name: { en: "asan", kr: "아산시" } },
    { rcode: 120800, areaLv: 2, name: { en: "cheonan", kr: "천안" } },
    { rcode: 120900, areaLv: 2, name: { en: "geumsan", kr: "금산군" } },
    { rcode: 121000, areaLv: 2, name: { en: "buyeo", kr: "부여군" } },
    { rcode: 121100, areaLv: 2, name: { en: "seocheon", kr: "서천군" } },
    { rcode: 121200, areaLv: 2, name: { en: "yesan", kr: "예산군" } },
    { rcode: 121300, areaLv: 2, name: { en: "cheongyang", kr: "청양군" } },
    { rcode: 121400, areaLv: 2, name: { en: "taean", kr: "태안군" } },
    { rcode: 121500, areaLv: 2, name: { en: "hongseong", kr: "홍성군" } },
  ],
  northGyeongsang: [
    { rcode: 130100, areaLv: 2, name: { en: "gyeongsan", kr: "경산시" } },
    { rcode: 130200, areaLv: 2, name: { en: "gyeongju", kr: "경주시" } },
    { rcode: 130300, areaLv: 2, name: { en: "gumi", kr: "구미시" } },
    { rcode: 130400, areaLv: 2, name: { en: "gimcheon", kr: "김천시" } },
    { rcode: 130500, areaLv: 2, name: { en: "mungyeong", kr: "문경시" } },
    { rcode: 130600, areaLv: 2, name: { en: "sangju", kr: "상주시" } },
    { rcode: 130700, areaLv: 2, name: { en: "andong", kr: "안동시" } },
    { rcode: 130800, areaLv: 2, name: { en: "yeongju", kr: "영주시" } },
    { rcode: 130900, areaLv: 2, name: { en: "yeongcheon", kr: "영천시" } },
    { rcode: 131000, areaLv: 2, name: { en: "pohang", kr: "포항시" } },
    { rcode: 131100, areaLv: 2, name: { en: "goryeong", kr: "고령군" } },
    { rcode: 131200, areaLv: 2, name: { en: "gunwi", kr: "군위군" } },
    { rcode: 131300, areaLv: 2, name: { en: "bonghwa", kr: "봉화군" } },
    { rcode: 131400, areaLv: 2, name: { en: "seongju", kr: "성주군" } },
    { rcode: 131500, areaLv: 2, name: { en: "yeongdeok", kr: "영덕군" } },
    { rcode: 131600, areaLv: 2, name: { en: "yeongyang", kr: "영양군" } },
    { rcode: 131700, areaLv: 2, name: { en: "yecheon", kr: "예천군" } },
    { rcode: 131800, areaLv: 2, name: { en: "ulleung", kr: "울릉군" } },
    { rcode: 131900, areaLv: 2, name: { en: "uljin", kr: "울진군" } },
    { rcode: 132000, areaLv: 2, name: { en: "uiseong", kr: "의성군" } },
    { rcode: 132100, areaLv: 2, name: { en: "cheongdo", kr: "청도군" } },
    { rcode: 132200, areaLv: 2, name: { en: "cheongsong", kr: "청송군" } },
    { rcode: 132300, areaLv: 2, name: { en: "chilgok", kr: "칠곡군" } },
  ],
  southGyeongsang: [
    { rcode: 140100, areaLv: 2, name: { en: "geoje", kr: "거제시" } },
    { rcode: 140200, areaLv: 2, name: { en: "gimhae", kr: "김해시" } },
    { rcode: 140300, areaLv: 2, name: { en: "miryang", kr: "밀양시" } },
    { rcode: 140400, areaLv: 2, name: { en: "sacheon", kr: "산천시" } },
    { rcode: 140500, areaLv: 2, name: { en: "yangsan", kr: "양산시" } },
    { rcode: 140600, areaLv: 2, name: { en: "jinju", kr: "진주시" } },
    { rcode: 140700, areaLv: 2, name: { en: "changwon", kr: "창원시" } },
    { rcode: 140800, areaLv: 2, name: { en: "tongyeong", kr: "통영시" } },
    { rcode: 140900, areaLv: 2, name: { en: "geochang", kr: "거창군" } },
    { rcode: 141000, areaLv: 2, name: { en: "goseong", kr: "고성군" } },
    { rcode: 141100, areaLv: 2, name: { en: "namhae", kr: "남해군" } },
    { rcode: 141200, areaLv: 2, name: { en: "sancheong", kr: "산청군" } },
    { rcode: 141300, areaLv: 2, name: { en: "uiryeong", kr: "의령군" } },
    { rcode: 141400, areaLv: 2, name: { en: "changnyeong", kr: "창녕군" } },
    { rcode: 141500, areaLv: 2, name: { en: "hadong", kr: "하동군" } },
    { rcode: 141600, areaLv: 2, name: { en: "haman", kr: "함안군" } },
    { rcode: 141700, areaLv: 2, name: { en: "hamyang", kr: "함양군" } },
    { rcode: 141800, areaLv: 2, name: { en: "hapcheon", kr: "합천군" } },
  ],
  northJeolla: [
    { rcode: 150100, areaLv: 2, name: { en: "gunsan", kr: "군산시" } },
    { rcode: 150200, areaLv: 2, name: { en: "gimje", kr: "김제시" } },
    { rcode: 150300, areaLv: 2, name: { en: "namwon", kr: "남원시" } },
    { rcode: 150400, areaLv: 2, name: { en: "iksan", kr: "익산시" } },
    { rcode: 150500, areaLv: 2, name: { en: "jeonju", kr: "전주시" } },
    { rcode: 150600, areaLv: 2, name: { en: "jeongeup", kr: "정읍시" } },
    { rcode: 150700, areaLv: 2, name: { en: "gochang", kr: "고창군" } },
    { rcode: 150800, areaLv: 2, name: { en: "muju", kr: "무주군" } },
    { rcode: 150900, areaLv: 2, name: { en: "buan", kr: "부안군" } },
    { rcode: 151000, areaLv: 2, name: { en: "sunchang", kr: "순창군" } },
    { rcode: 151100, areaLv: 2, name: { en: "wanju", kr: "완주군" } },
    { rcode: 151200, areaLv: 2, name: { en: "imsil", kr: "임실군" } },
    { rcode: 151300, areaLv: 2, name: { en: "jangsu", kr: "장수군" } },
    { rcode: 151400, areaLv: 2, name: { en: "jinan", kr: "진안군" } },
  ],
  southJeolla: [
    { rcode: 160100, areaLv: 2, name: { en: "gwangyang", kr: "광양시" } },
    { rcode: 160200, areaLv: 2, name: { en: "naju", kr: "나주시" } },
    { rcode: 160300, areaLv: 2, name: { en: "mokpo", kr: "목포시" } },
    { rcode: 160400, areaLv: 2, name: { en: "suncheon", kr: "순천시" } },
    { rcode: 160500, areaLv: 2, name: { en: "yeosu", kr: "여수시" } },
    { rcode: 160600, areaLv: 2, name: { en: "gangjin", kr: "강진군" } },
    { rcode: 160700, areaLv: 2, name: { en: "goheung", kr: "고흥군" } },
    { rcode: 160800, areaLv: 2, name: { en: "gokseong", kr: "곡성군" } },
    { rcode: 160900, areaLv: 2, name: { en: "gurye", kr: "구례군" } },
    { rcode: 161000, areaLv: 2, name: { en: "damyang", kr: "담양군" } },
    { rcode: 161100, areaLv: 2, name: { en: "muan", kr: "무안군" } },
    { rcode: 161200, areaLv: 2, name: { en: "boseong", kr: "보성군" } },
    { rcode: 161300, areaLv: 2, name: { en: "sinan", kr: "신안군" } },
    { rcode: 161400, areaLv: 2, name: { en: "yeonggwang", kr: "영광군" } },
    { rcode: 161500, areaLv: 2, name: { en: "yeongam", kr: "영암군" } },
    { rcode: 161600, areaLv: 2, name: { en: "wando", kr: "완도군" } },
    { rcode: 161700, areaLv: 2, name: { en: "jangseong", kr: "장성군" } },
    { rcode: 161800, areaLv: 2, name: { en: "jangheung", kr: "장흥군" } },
    { rcode: 161900, areaLv: 2, name: { en: "jindo", kr: "진도군" } },
    { rcode: 162000, areaLv: 2, name: { en: "hampyeong", kr: "함평군" } },
    { rcode: 162100, areaLv: 2, name: { en: "haenam", kr: "해남군" } },
    { rcode: 162200, areaLv: 2, name: { en: "hwasun", kr: "화순군" } },
  ],
  jeju: [
    { rcode: 170100, areaLv: 2, name: { en: "seogwipo", kr: "서귀포시" } },
    { rcode: 170200, areaLv: 2, name: { en: "jeju", kr: "제주시" } },
  ],
};
